### ISSUE TITLE
Add minimal App Bridge setup

### ISSUE THREAD

**Issue by iainmcampbell** [Shopify/webgen-embeddedapp#19]
per irl conversation with @tylerball, I’ll add a basic 'hello world' App Bridge setup to the embedded app frontend. also Polaris?

**Comment by katiedavis** [comment]
@iainmcampbell I didn't know you were doing this in this app and I took care of it here!
https://github.com/Shopify/webgen-embeddedapp/pull/20

**Comment by iainmcampbell** [comment]
oh nice! I didn't actually do it yet, so no worries. will close this issue then.
